#!/usr/bin/env python3
"""Generate skills/<id>.md contracts from registry/skills.json plus the contract table below.

The registry stays the single source of truth for ids, labels, outputs, and requires.
This file owns the prose that cannot be derived: what each skill takes in, and the bar
it has to clear. Run after editing either one:

    python tools/gen_skill_docs.py
"""
import io
import json

NL = chr(10)

CONTRACT = {
    "storytelling": {
        "inputs": ["raw material or topic", "audience", "one sentence of intent"],
        "bar_en": "A stranger can restate the throughline after one pass.",
        "bar_zh": "陌生人看過一次，能複述主線。",
    },
    "instructional-design": {
        "inputs": ["topic", "learner profile", "time budget"],
        "bar_en": "Every section maps to a stated objective and an assessment point.",
        "bar_zh": "每個段落都對應到一個學習目標與一個評量點。",
    },
    "research": {
        "inputs": ["question", "acceptable source types"],
        "bar_en": "Every factual claim carries a resolvable source; unverified claims are labelled.",
        "bar_zh": "每個事實主張都有可查證來源，未經查證的主張要標示出來。",
    },
    "infographic": {
        "inputs": ["the relationship to show", "canvas ratio"],
        "bar_en": "Cover the text and the diagram still reads.",
        "bar_zh": "遮住文字，圖還是看得懂。",
    },
    "data-visualization": {
        "inputs": ["dataset", "the claim the chart must support"],
        "bar_en": "Chart form matches the claim; encoding survives greyscale and colour blindness.",
        "bar_zh": "圖表形式對得上論點；轉灰階與色盲模擬後仍可判讀。",
    },
    "brand-system": {
        "inputs": ["brand pack reference"],
        "bar_en": "No hard-coded colour, font, or radius anywhere in the output.",
        "bar_zh": "產出裡沒有任何寫死的色碼、字體或圓角值。",
    },
    "presentation-design": {
        "inputs": ["outline from storytelling", "slide count", "projection distance"],
        "bar_en": "One idea per slide; body text legible from the back row.",
        "bar_zh": "一頁一個概念；最後一排看得清楚內文。",
    },
    "image-generation": {
        "inputs": ["scene description", "active style pack", "aspect ratio"],
        "bar_en": "Output sits inside the style pack and violates none of its avoid list.",
        "bar_zh": "產出落在風格包範圍內，且沒有踩到 avoid 清單。",
    },
    "motion": {
        "inputs": ["static composition", "duration", "platform"],
        "bar_en": "Motion carries meaning; nothing moves purely for decoration.",
        "bar_zh": "動態要承載意義，不做純裝飾的動作。",
    },
    "vision-judge": {
        "inputs": ["rendered output", "style pack", "threshold"],
        "bar_en": "Score is produced from an actual render, never from source code alone.",
        "bar_zh": "分數必須來自真的渲染畫面，不能只看原始碼。",
    },
    "text-check": {
        "inputs": ["rendered output", "output language"],
        "bar_en": "No overflow, no orphan lines, CJK breaks at legal points.",
        "bar_zh": "沒有文字溢出、沒有孤行，中文斷在合法的斷點。",
    },
    "brand-check": {
        "inputs": ["rendered output", "brand pack"],
        "bar_en": "Colour, type, spacing, and logo usage all resolve to brand tokens.",
        "bar_zh": "色彩、字體、間距與 logo 用法都能對回品牌 token。",
    },
    "auto-repair": {
        "inputs": ["QA reports", "threshold", "max repair rounds"],
        "bar_en": "Stops at the threshold or the round limit, and reports which one it hit.",
        "bar_zh": "在門檻或重跑次數上限停下，並回報是哪一個先到。",
    },
}


def main():
    reg = json.load(io.open("registry/skills.json", encoding="utf-8"))
    cats = {c["id"]: c["label"] for c in reg["categories"]}
    for s in reg["skills"]:
        c = CONTRACT[s["id"]]
        lines = [
            "# " + s["label"]["en"] + " / " + s["label"]["zh-TW"],
            "",
            "- **id**: `" + s["id"] + "`",
            "- **category**: " + cats[s["category"]]["en"] + " / " + cats[s["category"]]["zh-TW"],
            "- **requires**: " + (", ".join("`" + r + "`" for r in s["requires"]) or "none"),
            "- **outputs**: " + ", ".join("`" + o + "`" for o in s["outputs"]),
            "",
            "## What it does",
            "",
            "**EN** — " + s["summary"]["en"],
            "",
            "**繁中** — " + s["summary"]["zh-TW"],
            "",
            "## Inputs",
            "",
        ]
        lines += ["- " + i for i in c["inputs"]]
        lines += [
            "",
            "## Quality bar",
            "",
            "**EN** — " + c["bar_en"],
            "",
            "**繁中** — " + c["bar_zh"],
            "",
            "---",
            "",
            "*Generated by `tools/gen_skill_docs.py` from `registry/skills.json`. Do not edit by hand.*",
            "",
        ]
        io.open("skills/" + s["id"] + ".md", "w", encoding="utf-8", newline=NL).write(NL.join(lines))
    print("wrote " + str(len(reg["skills"])) + " skill contracts")


if __name__ == "__main__":
    main()
